### PR TITLE
Pdfs

### PR DESCRIPTION
**Pull request by davharris**
Final (?) PDFs for the main text and new supplement.

Once we finalize these, we can fill in line numbers in the rebuttal

### CODE REVIEW

**Comment by sdtaylor** [comment]
The latest commits do not change the main text, so these PDF's should be final.

**Comment by davharris** [comment]
Great. I've added line numbers to the reviewer response

**Comment by davharris** [comment]
And now I've rendered the reviewer response. Ready for final approval?

**Comment by ethanwhite** [comment]
Looks good. Once #238 is in (sorry for forgetting these until the last minute) we should be good to rebuild and call it final.

**Comment by sdtaylor** [comment]
@davharris this is now ready for one last render from master.

**Comment by davharris** [comment]
I get `pandoc-citeproc: reference senyondo2017 not found`, but can't figure out why. It's in the bibfile, and the spelling is correct.

Can one of you verify on your machine?

**Comment by sdtaylor** [comment]
there was a typo in the bibtex, I pushed a fix straight to master, can you try again?

**Comment by davharris** [comment]
Thanks @sdtaylor. Does anyone know/remember the best way to coerce bibtex into showing all the relevant information for our Zenodo products? Right now, they read like:

>Harris, D. J., E. White, and S. D. Taylor. 2017b. Weecology/forecasts: V0.0.2.

**Comment by sdtaylor** [comment]
maybe just put zenodo as the journal instead of the publisher? That and the DOI is all the relevant info.

**Comment by davharris** [comment]
Done. Ready to merge?

**Comment by ethanwhite** [comment]
One more small PR inbound

**Comment by ethanwhite** [comment]
#239 and then I'll stop.

**Comment by davharris** [comment]
Apart from that, are we good to go?

**Comment by sdtaylor** [comment]
LGTM

**Comment by ethanwhite** [comment]
:+1:

**Pull request merged**
