### PR TITLE
WIP: Fit models with observer effects

### PR DESCRIPTION
**Pull request by davharris**

### CODE REVIEW

**Comment by ethanwhite** [comment]
What's our status on this at the moment @davharris?

**Comment by davharris** [comment]
@ethanwhite Should be just about ready to go as soon as I figure out why HiperGator is complaining about memory usage...

**Comment by davharris** [comment]
Figured it out.  Was trying to store two gazillion MCMC samples on each core instead of two thousand 😵

**Comment by ethanwhite** [comment]
That would do it. When you've got the final tweaks working and in you can pull the WIP and ping me and I'll give it a read through and get it in.

**Comment by davharris** [comment]
Looks like it's finally working.  This branch is really messy, though (38 commits, 13 changed files). 

So I'm going to split the PR into two or three pieces: one for #61 (observer effects), one for #88, and possibly a third one with the remaining models.

Should be ready for review before our meeting on Monday.  Have a good weekend!

**Comment by davharris** [comment]
Superseded by #92 and #93

**Pull request closed without merging**
