### PR TITLE
Move data extraction/processing code into core

### PR DESCRIPTION
**Pull request by ethanwhite**
Also cleans up an old comment and reruns the notebook following the move.

### CODE REVIEW

**Comment by ethanwhite** [comment]
@davharris this commit gives you access to the data you need for #8 in `get_pop_ts_env_data()`. If you have time to give it a review then we can get it in an you can use that function to get the raw data for the SDMs.

**Comment by davharris** [comment]
Mostly looks good to me.  Are there any guarantees that `get_pop_ts_env_data` and `get_richness_ts_env_data` will return the same set of routes?

**Comment by ethanwhite** [comment]
Based on the code I think they have to. I played around with passing the output of `get_pop_ts_env_data` to `get_richness_ts_env_data` and working from there, but decided that, at least at a first glance, it would probably be more difficult to read.

**Comment by davharris** [comment]
Okay.  The other option would be to de-duplicate some of the operations like filtering out NAs and filtering by year so that they couldn't get out of sync.  But if these operations are only used twice, then maybe that's overkill.

If you decide that would be overkill, I don't have any objections to merging.

**Comment by ethanwhite** [comment]
Good call. What do you think about this instead.

**Pull request merged**
