### PR TITLE
Revise Discussion in response to questions about forecastability

### PR DESCRIPTION
**Pull request by ethanwhite**
This addresses the concerns of both the associate editor and Reviewer 2 about
the forecastability of BBS richness in the chosen time period. In adds a new
paragraph to the Discussion that expands on our previous discussion of these
points and calls for future research in this area.

Includes associated updates to the letter.

Alternative approach to #221.

### CODE REVIEW

**Comment by davharris** [comment]
Thanks Ethan. I think your changes to the text are better than mine.  

Looks good to me, except "most ecological forecasts are intended to be applied to the immediate future" might not be quite right.  Most *published* SDM predictions are for 2050 or some far-off date, I think. Although they're not really "intended to be applied" to anything.

**Comment by ethanwhite** [comment]
That's a good point about that language. What I was trying to convey was "we want to predict into the future where we expect this 'incredible dynamism' to continue, not to some stable point that occurred in the past."

**Comment by ethanwhite** [comment]
OK, I just tweaked the language to try to same more directly what I was thinking. See what you think.

**Comment by sdtaylor** [comment]
LGTM

**Comment by davharris** [comment]
LGTM. Thanks Ethan!

**Pull request merged**
