### PR TITLE
Add dynamic regression modeling to time-series forecasts

### PR DESCRIPTION
**Pull request by ethanwhite**
Adds a new time-series regression model (linear regression with ARIMA errors) to the suite of time-series models.

### CODE REVIEW

**Comment by davharris** [comment]
It's a bit hard for me to evaluate this with all the repeated double brackets. Could `.[[responsecol]][1:(length(.[[responsecol]]) - lag)]` be pulled out as a function?

**Comment by ethanwhite** [comment]
I agree, but I'm not sure how to make that work with `do`. Can I pass `.` to a function?

**Comment by davharris** [comment]
Yeah, you're already passing `.` to functions in your code.  It looks to me like you have two repeated patterns, which I've called f and g:

```
f = function(x, colname) x[[colname]][1:(nrow(x) - lag)]
g = function(x, colname) x[[colname]][(nrow(x) - lag + 1):nrow(x)]
```

I haven't tested it, so it's possible that I've made a typo somewhere, but I think you could do something like this: 

```
get_ts_forecasts <- function(grouped_tsdata, timecol, responsecol, exogcol, lag = 1){
  do(grouped_tsdata,
     timeperiod = g(., timecol),
     cast_naive = naive(f(., responsecol), lag),
     cast_avg = meanf(f(., responsecol), lag),
     cast_arima = forecast(auto.arima(f(., responsecol), seasonal = FALSE), h = lag),
     cast_exog_arima = forecast(auto.arima(f(., responsecol), xreg = f(., exogcol), seasonal = FALSE), xreg = g(., exogcol)),
     test_set = g(., exogcol)
  )
}
```

If `f and `g` had reasonable names (like "first chunk" and "last chunk" or something), I think it would improve the readability over the double brackets.

**Comment by ethanwhite** [comment]
That makes sense. Thanks. Testing an improved version now.

**Comment by ethanwhite** [comment]
OK, take a look at this one.

**Comment by davharris** [comment]
The changes to `get_ts_forecasts` make sense to me.  I can't view the notebook diff, though.

**Comment by ethanwhite** [comment]
Yeah, ignore the notebook diff, they still aren't very helpful at the moment. If you're happy with `get_ts_forecasts` go ahead and merge. Thanks for the helpful review!

**Pull request merged**
