### PR TITLE
Add script for downloading and adding elevation data to database

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by ethanwhite** [comment]
I just updated this PR to check the database to see if the data is already there before proceeding.

**Comment by sdtaylor** [comment]
should get_elev_data() be called download_elev_data() instead? Since it doesn't actually return the data.

**Comment by ethanwhite** [comment]
That's a good point. In fact, for consistency do you think it would be better to rename that function and then add a new `get_elev_data()` function that actually queries the database the returns the values? Is that basically what you've done in the other functions.

**Comment by sdtaylor** [comment]
yep, thats exactly what I do in the other scripts. get_xxx_data() downloads the data and puts it in the db if needed, but returns the values either way.

**Comment by ethanwhite** [comment]
Thanks. Just updated the PR to match that behavior and some of your syntax choice.

**Pull request merged**
