### PR TITLE
add plotting script

### PR DESCRIPTION
**Pull request by davharris**
The first 30 lines or so are to make the tidy data frame with all the results I sent over slack. The next chunk is playing with Figure 3 (#111). The rest is probably not useful; it's looking at observer-effect uncertainty.

### CODE REVIEW

**Comment by ethanwhite** [comment]
It would be good to get a version of this with the current state of all plotting code merged so that @sdtaylor and I can start helping out with finalizing figures.

**Comment by ethanwhite** [comment]
(oops hit `Ctrl-Enter` a little too fast)... Is this the current state of things or are there changes from the last few weeks that should go in before I merge this?

**Comment by davharris** [comment]
This will need to be updated to accommodate changes I'm making for predicting to 2050. Will have a working version by Monday.

**Comment by sdtaylor** [comment]
Can you change the filenames of the images to match #111, (fig1, fig2, etc)?. 
I can see which ones correspond to figs 1, 2, and 3, but I'm not sure which observer figure is which.

**Comment by davharris** [comment]
Based on some discussions with @ethanwhite, I've made some changes to the figures. The styling & labels still need work in some places, but the general idea is about right.

I've also added them to the manuscript in approximately the right places.  They don't always line up perfectly with the text, because the text hasn't caught up everywhere to the figures.  Hope this helps @sdtaylor

**Comment by ethanwhite** [comment]
Nice work @davharris! I'm going to go ahead and get this merged.

**Pull request merged**
