### PR TITLE
minor pipeline fixes

### PR DESCRIPTION
**Pull request by davharris**
* `AOU` -> `aou`

* simplified syntax for pulling out a vector from a data frame

### CODE REVIEW

**Comment by sdtaylor** [comment]
Yeah, `pull` is pretty sweet.  

Changing all cases back from #120? Don't forget line 161.

**Comment by davharris** [comment]
Ah, nice catch.

I think I know what's happening now.  Is it possible that the sqlite file you put on the T drive has an older version of the BBS data? Could you refresh the BBS-related tables to make sure? Sorry in advance if I'm wrong and this just makes extra work for you.

**Comment by sdtaylor** [comment]
I just verified it with a fresh install of retriever 2.0, the headers are all lower case in the sqlite db and the csv version.

**Comment by ethanwhite** [comment]
Looks like this is ready to go in now. Is that correct?

**Comment by davharris** [comment]
@ethanwhite Now it should be. Sorry for the confusion on my end in #120, and thanks to @sdtaylor for catching what I missed in this one.

**Pull request merged**
