### PR TITLE
Manuscript edits

### PR DESCRIPTION
**Pull request by davharris**
Also a new CSL file to help with #155.

Probably shouldn't be merged until after #117; merging this one first will probably cause a conflict in the "numbers" yaml file.

### CODE REVIEW

**Comment by sdtaylor** [comment]
I just rendered this with 
```
pandoc -V fontsize=12pt --bibliography refs.bib --csl=csl.csl draft.Rmd -o draft.pdf
```
Is that correct? It's not rendering any of the R code, and the GBM reference still says "others et al", but not the ridgeway reference.

**Comment by davharris** [comment]
I'd been using the `knit` button in Rstudio. Seems to use this incantation:

```pandoc +RTS -K512m -RTS draft.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output draft.pdf --template /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine /Library/TeX/texbin/pdflatex --variable graphics=yes --bibliography refs.bib --filter /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc-citeproc 
```

**Comment by davharris** [comment]
Your way probably gets all the important parts, though.

**Comment by ethanwhite** [comment]
As @davharris noted it looks like we need a rebase on this now.

**Comment by davharris** [comment]
@ethanwhite Done. Thanks for pointing out the problem.

**Comment by ethanwhite** [comment]
This all looks great to me. I made a couple of tiny fixes in the listed commits.

@sdtaylor - if/when your're happy go ahead and merge.

**Pull request merged**
