### PR TITLE
Full ms revision

### PR DESCRIPTION
**Pull request by ethanwhite**
This is a top to bottom revision of the ms. Major points of note:

* Completed expansion of Methods into prose
* Reworked flow of Results
* Recast @davharris's unnamed box item as 'Address unknown or unmeasured predictors'
* Added references throughout and created the bibtex file to go with them

### CODE REVIEW

**Comment by ethanwhite** [comment]
GitHub is pretty terrible at diffs for this sort of work.

`git diff --word-diff master` will work much better locally.

I think it's also fine to just merge and then provide thoughts during your next revision on the entire ms.

**Comment by davharris** [comment]
Thanks @ethanwhite! I had thought that there was a way to enable `word-diff` on Github with some URL magic, but turns out that's just for whitespace. I'll work on this once I've finished re-doing the future predictions code

**Comment by davharris** [comment]
I think I'll merge and edit, like you suggested in your comment.

**Comment by sdtaylor** [comment]
fyi I think github is doing a `--word-diff` when you press the "display the rich diff" button at the top of each file. It didn't work for Ethan's entire PR though, but it did work looking at individual commits.

**Pull request merged**
