### PR TITLE
Reply intro

### PR DESCRIPTION
**Pull request by sdtaylor**
Other peerj papers have this so I'm assuming we'll have one.

### CODE REVIEW

**Comment by davharris** [comment]
This seems like a good start. Do we want to go into more detail, or would that be unnecessary/repetitive? Also, it looks like we aren't given the editor's name (unless I'm just missing it), so maybe we just replace "XXX" with "Editor" in the salutation?

**Comment by sdtaylor** [comment]
I can't see the editors name anywhere either.

**Comment by sdtaylor** [comment]
Of the 4 random rebuttals intros I just read on peerj, this is longer than 3 of them, so I'd say any longer is unnecessary.

**Comment by ethanwhite** [comment]
:+1:

**Comment by davharris** [comment]
In the last sentence, I'd say

>More detailed responses to individual comments are **included** below.

Otherwise, LGTM! 👍

**Pull request merged**
